### ISSUE TITLE
How do I specify a site?

### ISSUE THREAD

**Issue by deviantintegral** [NBCUTechnology/pubstack#125]
Trying to get nbc.com up and running on this.

``` yml
synced_folder: ~/vagrant/projects/nbc/www

memory: 2048
cpus: 8

sites:
- subscription: nbcupublisher7
  shortname: install
  vhost:
    servername: local.install.publisher7.com
    documentroot: Publisher7/docroot
- subscription: nbcupublisher7
  shortname: update
  vhost:
    servername: local.update.publisher7.com
    documentroot: Publisher7/docroot
- subscription: nbcunbc
  shortname: nbcunbc
  vhost:
    servername: local.nbc.com
    documentroot: docroot
- subscription: nbcutelemundo
  shortname: nbcutelemundo
  vhost:
    servername: local.telemundo.com
    documentroot: Publisher7_nbcutelemundo/docroot
- subscription: nbcuuomerch
  shortname: nbcuuomerch
  vhost:
    servername: local.nbcuuomerch.com
    documentroot: Publisher7_nbcuuomerch/docroot
```

```
$ vagrant up
The docroot ~/vagrant/projects/nbc/www/Publisher7/docroot does not exist.
```

Where is it getting /Publisher7/ from? I'm not seeing any way to specify "this vm is for Y site from config.yml".
